web:
  port: 8080

endpoints:

  - name: App Health
    group: application
    url: "https://tm.hayats-labs.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: TLS Certificate
    group: security
    url: "https://tm.hayats-labs.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: Domain Expiration
    group: security
    url: "https://hayats-labs.com"
    interval: 24h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: Google
    group: external
    url: "https://www.google.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: YouTube
    group: external
    url: "https://www.youtube.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: GitHub
    group: external
    url: "https://github.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"