web:
  port: 8080


endpoints:

  - name: App Health
    group: application
    url: "https://tm.hayats-labs.com"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: TLS Certificate
    group: security
    url: "https://tm.hayats-labs.com"
    interval: 300s
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: Domain Expiration
    group: security
    url: "https://hayats-labs.com"
    interval: 300s
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: HTTP to HTTPS Redirect
    group: security
    url: "http://tm.hayats-labs.com"
    interval: 60s
    conditions:
      - "[STATUS] == 301"

  - name: Google
    group: external
    url: "https://www.google.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: GitHub
    group: external
    url: "https://github.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"